name: Deploy Backend

on:
  push:
    branches:
      - "*"

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Deploy to remote
        env:
          REMOTE_USER: snowflake
          REMOTE_HOST: 0.0.0.0
          REMOTE_BASE_DIR: homelabinator-unified
        run: |
          REMOTE_TARGET_DIR="${REMOTE_BASE_DIR}/${{ env.BRANCH_NAME }}"
          ssh "${REMOTE_USER}@${REMOTE_HOST}" "rm -rf ${REMOTE_TARGET_DIR}"
          rsync -avz --exclude '.**' --exclude '.*' ./ "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_TARGET_DIR}/"
          ssh "${REMOTE_USER}@${REMOTE_HOST}" "tmux kill-session -t homelabinator-unified 2>/dev/null || true"
          ssh "${REMOTE_USER}@${REMOTE_HOST}" "tmux new-session -d -s homelabinator-unified \"cd ~/homelabinator-unified && nix-shell -p nodejs_24 --command 'npm i && npm run prod'\""
